// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQROnnqeYBOyDGzNkJ0WKe5rfjDZB55o',
    appId: '1:118813037637:web:00df2c311d4e5a6bff7f2c',
    messagingSenderId: '118813037637',
    projectId: 'my-contact-address-app',
    authDomain: 'my-contact-address-app.firebaseapp.com',
    storageBucket: 'my-contact-address-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKczhUUIvBxjBCSLzZ-O0ej3QXtG4y3HA',
    appId: '1:118813037637:android:6ef29fbd8fe2bc3bff7f2c',
    messagingSenderId: '118813037637',
    projectId: 'my-contact-address-app',
    storageBucket: 'my-contact-address-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSTC35F7g2PLmdU7yBmkge-TWf6YPfyIw',
    appId: '1:118813037637:ios:5caf438798d512f1ff7f2c',
    messagingSenderId: '118813037637',
    projectId: 'my-contact-address-app',
    storageBucket: 'my-contact-address-app.firebasestorage.app',
    iosBundleId: 'com.example.myContactAddressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSTC35F7g2PLmdU7yBmkge-TWf6YPfyIw',
    appId: '1:118813037637:ios:5caf438798d512f1ff7f2c',
    messagingSenderId: '118813037637',
    projectId: 'my-contact-address-app',
    storageBucket: 'my-contact-address-app.firebasestorage.app',
    iosBundleId: 'com.example.myContactAddressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcQROnnqeYBOyDGzNkJ0WKe5rfjDZB55o',
    appId: '1:118813037637:web:965e738a2d611b03ff7f2c',
    messagingSenderId: '118813037637',
    projectId: 'my-contact-address-app',
    authDomain: 'my-contact-address-app.firebaseapp.com',
    storageBucket: 'my-contact-address-app.firebasestorage.app',
  );
}
